version: '3.8'
services:
    database:
        container_name: database
        image: mysql:8.0
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_USER: dev
            MYSQL_PASSWORD: DEV!++
            MYSQL_DATABASE: testrec_db
        ports:
            - '3306:3306'
        volumes:
            - ../mysql:/var/lib/mysql

    php:
        container_name: php
        build:
            context: ..
            dockerfile: docker/php/Dockerfile
        ports:
            - '9000:9000'
        volumes:
            - ../:/var/www/html/testrec
        links:
            - database
        depends_on:
            - database
    nginx:
        container_name: nginx
        image: nginx:stable-alpine
        ports:
            - '8080:80'
        volumes:
            - ../:/var/www/html/testrec
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./nginx/logs:/var/log/nginx:cached
        links:
            - php
        depends_on:
            - php
            - database
    phpmyadmin:
        container_name: phpmyadmin
        image: phpmyadmin
        restart: always
        ports:
            - 8081:80
        environment:
            - PMA_HOST=database
            - MYSQL_ROOT_PASSWORD=secret
            - MYSQL_DATABASE=testrec_db